// Imports an existing Node-backend data.json into the Cloudflare D1 database.
//
// Reads server/data/data.json (the Node deployment's store), backfills any
// missing fields to match the D1 schema (openTarget, displayMode,
// allViewMode), and emits a single SQL file with INSERT statements for
// categories, bookmarks, search_engines, and settings(all_view_mode).
//
//   Usage:
//     npm run import-d1 > sql/import.sql
//     wrangler d1 execute zyes-db --remote --file=sql/import.sql
//
// Idempotent-ish: uses INSERT OR IGNORE on PK columns so re-running won't
// duplicate rows by id. Sort orders and is_active are taken verbatim from
// the source file; D1's tuple ordering by sort_order is preserved on read.

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

interface SrcBookmark {
  id: string;
  categoryId: string;
  title: string;
  url: string;
  description?: string;
  icon?: string | null;
  openTarget?: 'new' | 'self';
  sortOrder?: number;
  createdAt?: string;
  updatedAt?: string;
}
interface SrcCategory {
  id: string;
  name: string;
  icon?: string;
  sortOrder?: number;
  displayMode?: 'compact' | 'detail';
  createdAt?: string;
}
interface SrcEngine {
  id: string;
  name: string;
  url: string;
  icon: string;
  isActive?: boolean;
}
interface SrcData {
  categories?: SrcCategory[];
  bookmarks?: SrcBookmark[];
  searchEngines?: SrcEngine[];
  settings?: { allViewMode?: 'compact' | 'detail' };
}

const DATA_PATH = resolve(process.cwd(), 'server/data/data.json');

function sqlStr(s: string | null | undefined): string {
  if (s === null || s === undefined) return 'NULL';
  return `'${String(s).replace(/'/g, "''")}'`;
}

function main(): void {
  let raw: string;
  try {
    raw = readFileSync(DATA_PATH, 'utf-8');
  } catch {
    console.error(`No data.json found at ${DATA_PATH}.`);
    console.error('Either run the Node backend once to create it, or set ZYES_DATA_DIR.');
    process.exit(1);
  }
  const data = JSON.parse(raw) as SrcData;

  const lines: string[] = [
    '-- Generated by scripts/import-to-d1.ts — import Node-backend data.json into D1.',
    '-- Run AFTER migrations/0001_init.sql so tables exist.',
    'BEGIN;',
  ];

  // Categories
  for (const c of data.categories ?? []) {
    lines.push(
      `INSERT OR IGNORE INTO categories (id, name, icon, sort_order, display_mode, created_at) VALUES (` +
        `${sqlStr(c.id)}, ${sqlStr(c.name)}, ${sqlStr(c.icon ?? '')}, ${c.sortOrder ?? 0}, ` +
        `${sqlStr(c.displayMode === 'compact' || c.displayMode === 'detail' ? c.displayMode : 'detail')}, ` +
        `${sqlStr(c.createdAt ?? new Date().toISOString())});`
    );
  }

  // Bookmarks
  for (const b of data.bookmarks ?? []) {
    lines.push(
      `INSERT OR IGNORE INTO bookmarks (id, category_id, title, url, description, icon, open_target, sort_order, created_at, updated_at) VALUES (` +
        `${sqlStr(b.id)}, ${sqlStr(b.categoryId ?? '')}, ${sqlStr(b.title)}, ${sqlStr(b.url)}, ` +
        `${sqlStr(b.description ?? '')}, ${sqlStr(b.icon ?? null)}, ` +
        `${sqlStr(b.openTarget === 'self' ? 'self' : 'new')}, ${b.sortOrder ?? 0}, ` +
        `${sqlStr(b.createdAt ?? new Date().toISOString())}, ${sqlStr(b.updatedAt ?? new Date().toISOString())});`
    );
  }

  // Search engines — replace the seeded set if the user has toggled is_active.
  if (Array.isArray(data.searchEngines) && data.searchEngines.length) {
    lines.push('-- Re-sync search engine isActive from the imported file:');
    for (const e of data.searchEngines) {
      lines.push(
        `INSERT INTO search_engines (id, name, url, icon, is_active) VALUES (` +
          `${sqlStr(e.id)}, ${sqlStr(e.name)}, ${sqlStr(e.url)}, ${sqlStr(e.icon)}, ${e.isActive ? 1 : 0}) ` +
          `ON CONFLICT(id) DO UPDATE SET is_active = excluded.is_active;`
      );
    }
  }

  // Global settings
  const allViewMode =
    data.settings?.allViewMode === 'compact' || data.settings?.allViewMode === 'detail'
      ? data.settings.allViewMode
      : 'detail';
  lines.push(
    `INSERT INTO settings (key, value) VALUES ('all_view_mode', ${sqlStr(allViewMode)}) ` +
      `ON CONFLICT(key) DO UPDATE SET value = excluded.value;`
  );

  lines.push('COMMIT;');
  process.stdout.write(lines.join('\n') + '\n');
}

main();
